version: '3.8'

services:
  web:
    build: .
    command: flask run --host=0.0.0.0 --port=5000 --cert=certs/cert.pem --key=certs/key.pem
    volumes:
      - .:/app
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development
      - DATABASE_URL=sqlite:///app.db
      - SECRET_KEY=your-secret-key
      - TWILIO_ACCOUNT_SID=your-twilio-sid
      - TWILIO_AUTH_TOKEN=your-twilio-token
      - TWILIO_WHATSAPP_FROM=whatsapp:+1234567890
      - MAIL_SERVER=smtp.example.com
      - MAIL_PORT=587
      - MAIL_USE_TLS=True
      - MAIL_USERNAME=your-email@example.com
      - MAIL_PASSWORD=your-email-password
      - GOOGLE_MAPS_API_KEY=your-google-maps-api-key

  worker:
    build: .
    command: celery -A tasks worker --loglevel=info
    volumes:
      - .:/app
    environment:
      - DATABASE_URL=sqlite:///app.db
      - TWILIO_ACCOUNT_SID=your-twilio-sid
      - TWILIO_AUTH_TOKEN=your-twilio-token
      - TWILIO_WHATSAPP_FROM=whatsapp:+1234567890
      - MAIL_SERVER=smtp.example.com
      - MAIL_PORT=587
      - MAIL_USE_TLS=True
      - MAIL_USERNAME=your-email@example.com
      - MAIL_PASSWORD=your-email-password
